# Generated by Django 4.1.3 on 2022-11-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_email_student_name_student_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
