# Generated by Django 4.1.3 on 2022-11-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_course_language_remove_course_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month_to_learn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
                ('email', models.CharField(default=0, max_length=200, unique=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('main_work', models.CharField(max_length=100, null=True)),
                ('experience', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
                ('email', models.CharField(default=0, max_length=200, unique=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('work_study_place', models.CharField(max_length=100, null=True)),
                ('has_own_notebook', models.BooleanField(help_text='Есть ли свой ноутбук?')),
                ('preferred_os', models.CharField(choices=[('windows', 'WINDOWS'), ('macOS', 'MAC'), ('linux', 'LINUX')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_started', models.DateField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.language')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mentor')),
            ],
        ),
    ]
